version: "3.5"

services:
  db:
    image: mysql:5.7
    container_name: ${COMPOSE_PROJECT_NAME}_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Password123
    ports:
      - '3306:3306'
    volumes:
      # mysql init DB and users
      - ./provision/mysql/init:/docker-entrypoint-initdb.d
      # mysql data bind mount
      - ./data/mysql:/var/lib/mysql
      # force local timezone
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

  adminer:
    image: adminer:latest
    container_name: ${COMPOSE_PROJECT_NAME}_adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - '8081:8080'
    volumes:
      # force local timezone      
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - "db"
